INSERT INTO students VALUES ('181CS101','Ishitha','0989383','a@gmail.com','female','2002-11-11','2019-07-19','Oman','200','S1');
INSERT INTO students VALUES ('181CS102','Aakash','698938300','aa@gmail.com','male','2002-11-11','2019-07-19','Quatar','202','S1');
INSERT INTO students VALUES ('181CS103','Arnav','788938300','ar@gmail.com','male','2001-11-11','2019-07-19','Italy','203','S2');

INSERT INTO users VALUES ('181CS224','Kruthika','Kruthika','admin');
INSERT INTO users VALUES ('181CS223','Sravani','Sravani','teacher');
INSERT INTO users VALUES ('181CS205','Janmansh','Janmansh','admin');
INSERT INTO users VALUES ('181CS101','Ishitha','Ishitha','student');
INSERT INTO users VALUES ('181CS102','Aakash','Aakash','student');
INSERT INTO users VALUES ('181CS103','Arnav','Arnav','student');

insert into teachers values ('181CS223', 'Sravani', '1234567891', 'ksk@gmail.com', 'chitradurga', 'female', '2010-3-12', '2021-2-1', 100000);
insert into teachers values ('181CS225', 'Anirudh', '67567891', 'ani@gmail.com', 'chithoor', 'male', '2010-3-12', '2021-2-1', 100000);
insert into teachers values ('181CS226', 'Akshitha', '976867891', '@akshithagmail.com', 'bengaluru', 'female', '2011-3-12', '2021-2-1', 80000);
insert into teachers values ('181CS234', 'Arushi', '9234567891', 'arushi@gmail.com', 'mangalore', 'female', '2001-3-12', '2021-3-1', 150000);
insert into teachers values ('181CS232', 'Sharath', '09456789001', 'sharath@gmail.com', 'hyderabad', 'male', '2002-3-12', '2021-1-1', 200000);

insert into subjects values ('CS251', 'DBMS', '191CS223', 'S1');
insert into subjects values ('CS250', 'COA', '191CS225', 'S2');
insert into subjects values ('CS252', 'OS', '191CS234', 'S1');
insert into subjects values ('CS253', 'DAA', '191CS226', 'S1');
insert into subjects values ('CS254', 'DBMS_LAB', '191CS232', 'S2');



